name: Deploy Components
run-name: Deploying Components
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
env:
  DEPLOY_CMD: ${{ github.ref == 'refs/heads/main' && 'pnpm run deploy:components -e prod' || 'pnpm run deploy:components -e dev' }}
jobs:
  Deploy-Components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.


      # Example 2
      - name: Get all changed section files
        id: changed-section-files
        uses: tj-actions/changed-files@v41
        with:
          files: sections/*.liquid

      - name: List all changed files markdown files
        if: steps.changed-section-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-section-files.outputs.all_changed_files }}
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            echo "$DEPLOY_CMD -f $file"
          done

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: 'yarn'

      # - name: Preparing
      #   run: yarn install --frozen-lockfile

      # - name: Building
      #   run: yarn build

